### ISSUE TITLE
Trustworthiness and continuity calculation

### ISSUE THREAD

**Issue by ms609** [csoneson/dreval#2]
Hi Charlotte,

Thanks for the package; I've found the trustworthiness and continuity calculation functions useful.

I think the calculations might need a little tweaking, as I occasionally get values outside the range `]0, 1[`.  It looks to me that rankReference and rankLowDim should have one subtracted from them (and the diagonals set to `NA`?), in order to exclude the _i_ == _j_ case in **r**(_x<sub>i</sub>; x<sub>j</sub>_); (per Venna & Kaski 2001 table 1).

I wonder whether it's also worth noting in the docs that your code assumes that _k_ < _N_ / 2, and perhaps validating user input accordingly?  I'm seeing trustworthiness values > 1 with good mappings when _k_ is large relative to _N_.

**Comment by csoneson** [comment]
Hi @ms609 - thanks for noticing this! I think you're right - I'll fix this and take the opportunity to also add some more extensive tests. I'll try to get to this in the coming days.

**Comment by ms609** [comment]
Cheers – if it helps to cross-reference, I've ended up implementing values of _k_ > _N_ / 2 at https://github.com/ms609/TreeDist/blob/master/R/trustworthiness.R .

**Comment by csoneson** [comment]
I just pushed [v0.1.5](https://github.com/csoneson/dreval/commit/c9e15c20cab411ca1c4344bdb0c768a7f41336bf), which fixes the issue with the nearest neighbors. It also now allows k>=N/2 (following e.g. http://proceedings.mlr.press/v4/lee08a/lee08a.pdf), and results agree with `TreeDist` :) Thanks again for noticing!
